---
title: "HR: Employment contract management."
type: feature
description: |
  "Manage following configurations related to employeement contract management:
  Collective agreement, Qualification, Qualification level, Paygrid, Employments, SMIC value, 
  Contract types, Amendment types, Probation periods,
  Health mutual rejection reason."
