
package com.qas.web_2005_02;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-12T15:14:19.665+02:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "QAFault", targetNamespace = "http://www.qas.com/web-2005-02")
public class Fault extends Exception {
    
    private com.qas.web_2005_02.QAFault qaFault;

    public Fault() {
        super();
    }
    
    public Fault(String message) {
        super(message);
    }
    
    public Fault(String message, Throwable cause) {
        super(message, cause);
    }

    public Fault(String message, com.qas.web_2005_02.QAFault qaFault) {
        super(message);
        this.qaFault = qaFault;
    }

    public Fault(String message, com.qas.web_2005_02.QAFault qaFault, Throwable cause) {
        super(message, cause);
        this.qaFault = qaFault;
    }

    public com.qas.web_2005_02.QAFault getFaultInfo() {
        return this.qaFault;
    }
}
