/**
 * Copyright (c) 2012-2014 Axelor. All Rights Reserved.
 *
 * The contents of this file are subject to the Common Public
 * Attribution License Version 1.0 (the “License”); you may not use
 * this file except in compliance with the License. You may obtain a
 * copy of the License at:
 *
 * http://license.axelor.com/.
 *
 * The License is based on the Mozilla Public License Version 1.1 but
 * Sections 14 and 15 have been added to cover use of software over a
 * computer network and provide for limited attribution for the
 * Original Developer. In addition, Exhibit A has been modified to be
 * consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an “AS IS”
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is part of "Axelor Business Suite", developed by
 * Axelor exclusively.
 *
 * The Original Developer is the Initial Developer. The Initial Developer of
 * the Original Code is Axelor.
 *
 * All portions of the code written by Axelor are
 * Copyright (c) 2012-2014 Axelor. All Rights Reserved.
 */
package com.qas.web_2005_02;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-12T15:14:19.685+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ProWeb", 
                  wsdlLocation = "http://ip.axelor.com:2021/proweb.wsdl",
                  targetNamespace = "http://www.qas.com/web-2005-02") 
public class ProWeb extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.qas.com/web-2005-02", "ProWeb");
    public final static QName QAPortType = new QName("http://www.qas.com/web-2005-02", "QAPortType");
    static {
        URL url = null;
        try {
            url = new URL("http://ip.axelor.com:2021/proweb.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProWeb.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ip.axelor.com:2021/proweb.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProWeb(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProWeb() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QAPortType
     */
    @WebEndpoint(name = "QAPortType")
    public QAPortType getQAPortType() {
        return super.getPort(QAPortType, QAPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QAPortType
     */
    @WebEndpoint(name = "QAPortType")
    public QAPortType getQAPortType(WebServiceFeature... features) {
        return super.getPort(QAPortType, QAPortType.class, features);
    }

}
