/**
 * Copyright (c) 2012-2014 Axelor. All Rights Reserved.
 *
 * The contents of this file are subject to the Common Public
 * Attribution License Version 1.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a
 * copy of the License at:
 *
 * http://license.axelor.com/.
 *
 * The License is based on the Mozilla Public License Version 1.1 but
 * Sections 14 and 15 have been added to cover use of software over a
 * computer network and provide for limited attribution for the
 * Original Developer. In addition, Exhibit A has been modified to be
 * consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Original Code is part of "Axelor Business Suite", developed by
 * Axelor exclusively.
 *
 * The Original Developer is the Initial Developer. The Initial Developer of
 * the Original Code is Axelor.
 *
 * All portions of the code written by Axelor are
 * Copyright (c) 2012-2014 Axelor. All Rights Reserved.
 */
package com.qas.web_2005_02;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-12T15:14:19.675+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://www.qas.com/web-2005-02", name = "QAPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QAPortType {

    @WebResult(name = "QALicenceInfo", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoGetLicenseInfo", action = "http://www.qas.com/web-2005-02/DoGetLicenseInfo")
    public QALicenceInfo doGetLicenseInfo() throws Fault;

    @WebResult(name = "QAData", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoGetData", action = "http://www.qas.com/web-2005-02/DoGetData")
    public QAData doGetData() throws Fault;

    @WebResult(name = "QAExampleAddresses", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoGetExampleAddresses", action = "http://www.qas.com/web-2005-02/DoGetExampleAddresses")
    public QAExampleAddresses doGetExampleAddresses(
        @WebParam(partName = "body", name = "QAGetExampleAddresses", targetNamespace = "http://www.qas.com/web-2005-02")
        QAGetExampleAddresses body
    ) throws Fault;

    @WebResult(name = "Picklist", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoRefine", action = "http://www.qas.com/web-2005-02/DoRefine")
    public Picklist doRefine(
        @WebParam(partName = "body", name = "QARefine", targetNamespace = "http://www.qas.com/web-2005-02")
        QARefine body
    ) throws Fault;

    @WebResult(name = "Address", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoGetAddress", action = "http://www.qas.com/web-2005-02/DoGetAddress")
    public Address doGetAddress(
        @WebParam(partName = "body", name = "QAGetAddress", targetNamespace = "http://www.qas.com/web-2005-02")
        QAGetAddress body
    ) throws Fault;

    @WebResult(name = "QASearchResult", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoSearch", action = "http://www.qas.com/web-2005-02/DoSearch")
    public QASearchResult doSearch(
        @WebParam(partName = "body", name = "QASearch", targetNamespace = "http://www.qas.com/web-2005-02")
        QASearch body
    ) throws Fault;

    @WebResult(name = "QASearchOk", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoCanSearch", action = "http://www.qas.com/web-2005-02/DoCanSearch")
    public QASearchOk doCanSearch(
        @WebParam(partName = "body", name = "QACanSearch", targetNamespace = "http://www.qas.com/web-2005-02")
        QACanSearch body
    ) throws Fault;

    @WebResult(name = "QALayouts", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoGetLayouts", action = "http://www.qas.com/web-2005-02/DoGetLayouts")
    public QALayouts doGetLayouts(
        @WebParam(partName = "body", name = "QAGetLayouts", targetNamespace = "http://www.qas.com/web-2005-02")
        QAGetLayouts body
    ) throws Fault;

    @WebResult(name = "QAPromptSet", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoGetPromptSet", action = "http://www.qas.com/web-2005-02/DoGetPromptSet")
    public QAPromptSet doGetPromptSet(
        @WebParam(partName = "body", name = "QAGetPromptSet", targetNamespace = "http://www.qas.com/web-2005-02")
        QAGetPromptSet body
    ) throws Fault;

    @WebResult(name = "QASystemInfo", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
    @WebMethod(operationName = "DoGetSystemInfo", action = "http://www.qas.com/web-2005-02/DoGetSystemInfo")
    public QASystemInfo doGetSystemInfo() throws Fault;
}
