/*
 * Axelor Business Solutions
 *
 * Copyright (C) 2020 Axelor (<http://axelor.com>).
 *
 * This program is free software: you can redistribute it and/or  modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.qas.web_2005_02;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2 2012-09-12T15:14:19.675+02:00 Generated source
 * version: 2.6.2
 */
@WebService(targetNamespace = "http://www.qas.com/web-2005-02", name = "QAPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QAPortType {

  @WebResult(
    name = "QALicenceInfo",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(
    operationName = "DoGetLicenseInfo",
    action = "http://www.qas.com/web-2005-02/DoGetLicenseInfo"
  )
  public QALicenceInfo doGetLicenseInfo() throws Fault;

  @WebResult(name = "QAData", targetNamespace = "http://www.qas.com/web-2005-02", partName = "body")
  @WebMethod(operationName = "DoGetData", action = "http://www.qas.com/web-2005-02/DoGetData")
  public QAData doGetData() throws Fault;

  @WebResult(
    name = "QAExampleAddresses",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(
    operationName = "DoGetExampleAddresses",
    action = "http://www.qas.com/web-2005-02/DoGetExampleAddresses"
  )
  public QAExampleAddresses doGetExampleAddresses(
      @WebParam(
            partName = "body",
            name = "QAGetExampleAddresses",
            targetNamespace = "http://www.qas.com/web-2005-02"
          )
          QAGetExampleAddresses body)
      throws Fault;

  @WebResult(
    name = "Picklist",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(operationName = "DoRefine", action = "http://www.qas.com/web-2005-02/DoRefine")
  public Picklist doRefine(
      @WebParam(
            partName = "body",
            name = "QARefine",
            targetNamespace = "http://www.qas.com/web-2005-02"
          )
          QARefine body)
      throws Fault;

  @WebResult(
    name = "Address",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(operationName = "DoGetAddress", action = "http://www.qas.com/web-2005-02/DoGetAddress")
  public Address doGetAddress(
      @WebParam(
            partName = "body",
            name = "QAGetAddress",
            targetNamespace = "http://www.qas.com/web-2005-02"
          )
          QAGetAddress body)
      throws Fault;

  @WebResult(
    name = "QASearchResult",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(operationName = "DoSearch", action = "http://www.qas.com/web-2005-02/DoSearch")
  public QASearchResult doSearch(
      @WebParam(
            partName = "body",
            name = "QASearch",
            targetNamespace = "http://www.qas.com/web-2005-02"
          )
          QASearch body)
      throws Fault;

  @WebResult(
    name = "QASearchOk",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(operationName = "DoCanSearch", action = "http://www.qas.com/web-2005-02/DoCanSearch")
  public QASearchOk doCanSearch(
      @WebParam(
            partName = "body",
            name = "QACanSearch",
            targetNamespace = "http://www.qas.com/web-2005-02"
          )
          QACanSearch body)
      throws Fault;

  @WebResult(
    name = "QALayouts",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(operationName = "DoGetLayouts", action = "http://www.qas.com/web-2005-02/DoGetLayouts")
  public QALayouts doGetLayouts(
      @WebParam(
            partName = "body",
            name = "QAGetLayouts",
            targetNamespace = "http://www.qas.com/web-2005-02"
          )
          QAGetLayouts body)
      throws Fault;

  @WebResult(
    name = "QAPromptSet",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(
    operationName = "DoGetPromptSet",
    action = "http://www.qas.com/web-2005-02/DoGetPromptSet"
  )
  public QAPromptSet doGetPromptSet(
      @WebParam(
            partName = "body",
            name = "QAGetPromptSet",
            targetNamespace = "http://www.qas.com/web-2005-02"
          )
          QAGetPromptSet body)
      throws Fault;

  @WebResult(
    name = "QASystemInfo",
    targetNamespace = "http://www.qas.com/web-2005-02",
    partName = "body"
  )
  @WebMethod(
    operationName = "DoGetSystemInfo",
    action = "http://www.qas.com/web-2005-02/DoGetSystemInfo"
  )
  public QASystemInfo doGetSystemInfo() throws Fault;
}
