package com.axelor.apps.account.einvoice.eu.e_arvetekeskus.erp;

import jakarta.jws.*;
import jakarta.jws.soap.SOAPBinding;

import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2021-01-08T13:56:35.237+02:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://e-arvetekeskus.eu/erp", name = "ErpDataExchange")
@XmlSeeAlso({ObjectFactory.class, com.axelor.apps.account.einvoice.ee.pangaliit.arveldused.e_arve.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ErpDataExchange {

    @WebMethod(operationName = "RegistryImport")
    @WebResult(name = "RegistryImportResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "RegistryImportResponse")
    public RegistryImportResponse registryImport(
        @WebParam(partName = "RegistryImportRequest", name = "RegistryImportRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        RegistryImportRequest registryImportRequest
    );

    @WebMethod(operationName = "CostReportAttachment")
    @WebResult(name = "CostReportAttachmentResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "CostReportAttachmentResponse")
    public CostReportAttachmentResponseType costReportAttachment(
        @WebParam(partName = "CostReportAttachmentRequest", name = "CostReportAttachmentRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        CostReportAttachmentRequestType costReportAttachmentRequest
    );

    @WebMethod(operationName = "SaleInvoiceBuyStatus")
    @WebResult(name = "SaleInvoiceBuyStatusResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "SaleInvoiceBuyStatusResponse")
    public SaleInvoiceBuyStatusResponseType saleInvoiceBuyStatus(
        @WebParam(partName = "SaleInvoiceBuyStatusRequest", name = "SaleInvoiceBuyStatusRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        SaleInvoiceBuyStatusRequestType saleInvoiceBuyStatusRequest
    );

    @WebMethod(operationName = "BuyInvoiceExport")
    @WebResult(name = "BuyInvoiceExportResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "BuyInvoiceExportResponse")
    public EInvoiceResponseType buyInvoiceExport(
        @WebParam(partName = "BuyInvoiceExportRequest", name = "BuyInvoiceExportRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        BuyInvoiceReqType buyInvoiceExportRequest
    );

    @WebMethod(operationName = "InvoiceAttachment")
    @WebResult(name = "InvoiceAttachmentResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "InvoiceAttachmentResponse")
    public InvoiceAttachmentResponseType invoiceAttachment(
        @WebParam(partName = "InvoiceAttachmentRequest", name = "InvoiceAttachmentRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        InvoiceAttachmentRequestType invoiceAttachmentRequest
    );

    @WebMethod(operationName = "CompanyStatus")
    @WebResult(name = "CompanyStatusResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "CompanyStatusResponse")
    public CompanyStatusResponseType companyStatus(
        @WebParam(partName = "CompanyStatusRequest", name = "CompanyStatusRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        CompanyStatusRequestType companyStatusRequest
    );

    @WebMethod(operationName = "EInvoice")
    @WebResult(name = "EInvoiceResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "EInvoiceResponse")
    public SimpleResponseType eInvoice(
        @WebParam(partName = "EInvoiceRequest", name = "EInvoiceRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        EInvoiceRequest eInvoiceRequest
    );

    @WebMethod(operationName = "RejectConfirmation")
    @WebResult(name = "RejectConfirmationResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "RejectConfirmationResponse")
    public SimpleResponseType rejectConfirmation(
        @WebParam(partName = "RejectConfirmationRequest", name = "RejectConfirmationRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        RejectConfirmationRequestType rejectConfirmationRequest
    );

    @WebMethod(operationName = "BuyInvoiceRegistered")
    @WebResult(name = "BuyInvoiceRegisteredResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "BuyInvoiceRegisteredResponse")
    public SimpleResponseType buyInvoiceRegistered(
        @WebParam(partName = "BuyInvoiceRegisteredRequest", name = "BuyInvoiceRegisteredRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        BuyInvoiceRegisteredReqType buyInvoiceRegisteredRequest
    );

    @WebMethod(operationName = "BuyInvoice")
    @Oneway
    public void buyInvoice(
        @WebParam(partName = "BuyInvoiceRequest", name = "BuyInvoiceRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        BuyInvoiceReqType buyInvoiceRequest
    );

    @WebMethod(operationName = "CostReportExport")
    @WebResult(name = "CostReportExportResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "CostReportExportResponse")
    public CostReportExportResponseType costReportExport(
        @WebParam(partName = "CostReportExportRequest", name = "CostReportExportRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        CostReportExportRequestType costReportExportRequest
    );

    @WebMethod(operationName = "DimensionRegistry")
    @WebResult(name = "DimensionRegistryResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "DimensionRegistryResponse")
    public DimensionRegistryResponse dimensionRegistry(
        @WebParam(partName = "DimensionRegistryRequest", name = "DimensionRegistryRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        DimensionRegistryRequestType dimensionRegistryRequest
    );

    @WebMethod(operationName = "AccountPlan")
    @WebResult(name = "AccountPlanResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "AccountPlanResponse")
    public SimpleResponseType accountPlan(
        @WebParam(partName = "AccountPlanRequest", name = "AccountPlanRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        AccountPlanRequestType accountPlanRequest
    );

    @WebMethod(operationName = "BuyInvoicePaid")
    @WebResult(name = "BuyInvoicePaidResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "BuyInvoicePaidResponse")
    public SimpleResponseType buyInvoicePaid(
        @WebParam(partName = "BuyInvoicePaidRequest", name = "BuyInvoicePaidRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        BuyInvoicePaidReqType buyInvoicePaidRequest
    );

    @WebMethod(operationName = "BuyInvoicePdf")
    @WebResult(name = "BuyInvoicePdfResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "BuyInvoicePdfResponse")
    public BuyInvoicePdfResponse buyInvoicePdf(
        @WebParam(partName = "BuyInvoicePdfRequest", name = "BuyInvoicePdfRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        BuyInvoicePdfRequest buyInvoicePdfRequest
    );

    @WebMethod(operationName = "SaleInvoiceExport")
    @WebResult(name = "SaleInvoiceExportResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "SaleInvoiceExportResponse")
    public EInvoiceRespoonseType saleInvoiceExport(
        @WebParam(partName = "SaleInvoiceExportRequest", name = "SaleInvoiceExportRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        SaleInvoiceExportReqType saleInvoiceExportRequest
    );

    @WebMethod(operationName = "HasBuyInvoice")
    @WebResult(name = "HasBuyInvoiceResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "HasBuyInvoiceResponse")
    public String hasBuyInvoice(
        @WebParam(partName = "HasBuyInvoiceRequest", name = "HasBuyInvoiceRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        BuyInvoiceReqType hasBuyInvoiceRequest
    );

    @WebMethod(operationName = "ClientRegistry")
    @WebResult(name = "ClientRegistryResponse", targetNamespace = "http://e-arvetekeskus.eu/erp", partName = "ClientRegistryResponse")
    public SimpleResponseType clientRegistry(
        @WebParam(partName = "ClientRegistryRequest", name = "ClientRegistryRequest", targetNamespace = "http://e-arvetekeskus.eu/erp")
        ClientRegistryRequestType clientRegistryRequest
    );
}
