/*
 * Axelor Business Solutions
 *
 * Copyright (C) 2005-2026 Axelor (<http://axelor.com>).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.axelor.apps.account.web;

import com.axelor.apps.account.db.AnalyticDistributionTemplate;
import com.axelor.apps.account.db.AnalyticMoveLine;
import com.axelor.apps.account.db.repo.AnalyticLine;
import com.axelor.apps.account.db.repo.AnalyticMoveLineRepository;
import com.axelor.apps.account.model.AnalyticLineModel;
import com.axelor.apps.account.service.analytic.AnalyticMoveLineComputeService;
import com.axelor.apps.account.service.analytic.AnalyticMoveLineParentService;
import com.axelor.apps.base.service.exception.TraceBackService;
import com.axelor.inject.Beans;
import com.axelor.rpc.ActionRequest;
import com.axelor.rpc.ActionResponse;
import com.axelor.rpc.Context;
import java.math.BigDecimal;
import java.util.Collections;
import java.util.Objects;
import java.util.Optional;

public class AnalyticMoveLineController {

  public void computePercentage(ActionRequest request, ActionResponse response) {
    try {
      AnalyticMoveLine analyticMoveLine = request.getContext().asType(AnalyticMoveLine.class);
      AnalyticLineModel parent =
          Beans.get(AnalyticMoveLineParentService.class)
              .getModelUsingAnalyticMoveLine(analyticMoveLine, request.getContext());

      AnalyticMoveLineComputeService analyticMoveLineComputeService =
          Beans.get(AnalyticMoveLineComputeService.class);

      BigDecimal percentage =
          parent != null
              ? analyticMoveLineComputeService.computePercentage(
                  analyticMoveLine, parent.getLineAmount())
              : analyticMoveLineComputeService.computePercentage(analyticMoveLine);
      response.setValue("percentage", percentage);
    } catch (Exception e) {
      TraceBackService.trace(response, e);
    }
  }

  /**
   * Called on change of the analytic distribution lines of an analytic line. As soon as the
   * distribution no longer matches the template it was generated from, the template is cleared,
   * because it does not describe the line any more. Removing a line is the main case, adding one is
   * handled the same way.
   *
   * <p>The context is the parent analytic line (move, invoice, sale order, purchase order, contract
   * or expense line), not the analytic move line itself. Reversal lines are left out of the count:
   * they come on top of the distribution generated by the template.
   */
  public void clearDistributionTemplateOnLineChange(
      ActionRequest request, ActionResponse response) {
    try {
      Context context = request.getContext();
      Class<?> contextClass = context.getContextClass();

      if (contextClass == null || !AnalyticLine.class.isAssignableFrom(contextClass)) {
        return;
      }

      AnalyticLine analyticLine = (AnalyticLine) context.asType(contextClass);
      AnalyticDistributionTemplate analyticDistributionTemplate =
          analyticLine.getAnalyticDistributionTemplate();

      if (analyticDistributionTemplate == null) {
        return;
      }

      int templateLineCount =
          Optional.of(analyticDistributionTemplate)
              .map(AnalyticDistributionTemplate::getAnalyticDistributionLineList)
              .orElse(Collections.emptyList())
              .size();

      if (this.countDistributionLines(analyticLine) != templateLineCount) {
        response.setValue("analyticDistributionTemplate", null);
      }
    } catch (Exception e) {
      TraceBackService.trace(response, e);
    }
  }

  /** Counts the analytic move lines of an analytic line, leaving the reversal ones out. */
  protected long countDistributionLines(AnalyticLine analyticLine) {
    return Optional.of(analyticLine)
        .map(AnalyticLine::getAnalyticMoveLineList)
        .orElse(Collections.emptyList())
        .stream()
        .filter(Objects::nonNull)
        .filter(
            analyticMoveLine ->
                !Objects.equals(
                    analyticMoveLine.getSubTypeSelect(),
                    AnalyticMoveLineRepository.SUB_TYPE_REVERSE))
        .count();
  }
}
